swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      description: Returns all todos available in the database
      operationId: GetAllTodos
      responses:
        200:
          description: An array of todos
          schema:
            type: array
            items:
              $ref: "#/definitions/Todo"
    post:
      description: Add a new todo
      operationId: AddTodo
      produces:
      - application/json
      parameters:
      - name: todo
        in: body
        description: The todo to be added
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        200:
          description: Successful todo add
      x-swagger-router-controller: AddTodo
  /todo/{id}:
    get:
      description: Retrieve a single todo by ID
      operationId: FindTodoById
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of the todo to get
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Todo response
          schema:
            $ref: "#/definitions/Todo"
      x-swagger-router-controller: FindTodoById
    delete:
      description: Delete a single todo by ID
      operationId: DeleteTodoById
      parameters:
      - name: id
        in: path
        description: ID of the todo to delete
        required: true
        type: integer
        format: int64
      responses:
        204:
          description: Todo deleted
      x-swagger-router-controller: DeleteTodoById
    put:
      description: Update a single todo by ID
      operationId: UpdateTodoById
      parameters:
      - name: id
        in: path
        description: ID of the todo to update
        required: true
        type: integer
        format: int64
      - name: updated_todo
        in: body
        description: The updated todo
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        200:
          description: Todo updated
        400:
          description: Yikes! An Error!
      x-swagger-router-controller: UpdateTodoById
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Todo:
    type: object
    properties:
      todo_id:
        type: integer
        description: Id for the todo
      todo:
        type: string
        description: The todo item
      datecreated:
        type: string
        format: date-time
        description: Time-stamp when the todo was created, set by server
      author:
        type: string
        description: Creator or owner of the todo
      duedate:
        type: string
        format: date-time
        description: When the todo is due
      completed:
        type: boolean
        description: Indicates if the todo has been completed or not
